VIA_ENABLE = yes
VIAL_ENABLE = yes

LTO_ENABLE = yes

WS2812_DRIVER = vendor
RGBLIGHT_ENABLE = yes

QMK_SETTINGS = yes
DYNAMIC_TAPPING_TERM_ENABLE = yes
TAP_DANCE_ENABLE = yes
COMBO_ENABLE = yes
# KEY_OVERRIDE_ENABLE = yes
# EXTRAKEY_ENABLE = yes
# MAGIC_ENABLE = yes
# GRAVE_ESC_ENABLE = yes
# MOUSEKEY_ENABLE = yes
# NKRO_ENABLE = yes # 6キー以上同時
# ENCODER_MAP_ENABLE = yes
# OLED_ENABLE = yes
